version: '3.6'
services:
  dasaapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: dasa
      DB_HOST: db
      DB_PORT: 5432
      DB_DIALECT: postgres
    image: dasaapp
    command: nodemon server
    ports:
      - "8082:8082"
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    links:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dasa
    volumes:
      - "./database/data:/var/lib/postgres"