version: '3.6'
services:
  dasaapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: postgresql://root:root@db:5432/dasa
    image: dasaapp
    command: nodemon server
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    links:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dasa
    volumes:
      - "./database/data:/var/lib/postgres"